#-------------------------------
# General Site Settings
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Raul García"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 5


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  description = "Creative Portfolio Theme for Hugo"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Sobre Mi"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Portafolio"
    url = "/works/"
    weight = 3

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 4

  [[menu.main]]
  name = "Contacto"
  url = "/contact/"
  weight = 5


  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "Raul García"
    author__bio = "Hola, Soy Raul – Developer. I'm a creative and curious person who has a lot of experience and fond moments working with design, websites, and marketing."
    author__avatar = "https://via.placeholder.com/400x400"

  # Social Links
  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "ion-logo-facebook"
    name = "Facebook"
    link = "https://facebook.com"

  [[params.social]]
    icon = "ion-logo-instagram"
    name = "Instagram"
    link = "https://instagram.com"

  [[params.social]]
    icon = "ion-logo-pinterest"
    name = "Pinterest"
    link = "https://pinterest.com"

  [[params.social]]
    icon = "ion-logo-github"
    name = "Github"
    link = "https://github.com"

  [[params.social]]
    icon = "ion-logo-vimeo"
    name = "Vimeo"
    link = "https://vimeo.com"

  # Example of adding a new link to the footer:
  # [[params.social]]
  #   icon = "ion-logo-youtube"
  #   name = "Youtube"
  #   link = "https://youtube.com"

  # Other icons can be found at https://ionicons.com/v4/


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero__title = "Hola, Soy Raul"
    hero__description = "Ingeniero de sistemas con más de una década de experiencia en el desarrollo de soluciones de integración, particularmente en los sectores bancario y de telecomunicaciones, aprovechando arquitecturas orientadas a servicios (SOA)."
    hero__image = "/images/raul-garcia.jpg"


    #-------------------------------
    # Logos Settings
    [params.logos]
      enable = true
      logos__title = "He colaborado con empresas destacadas"

    [[params.logo_item]]
      name = "Kruger"
      link = "https://krugercorp.com/"
      image = "/images/hero-section/kruger.svg"

    [[params.logo_item]]
      name = "PLAY DIGITAL consulting"
      link = "https://www.playdigitalconsulting.com/en"
      image = "/images/hero-section/play.svg"

    [[params.logo_item]]
      name = "Ceteris"
      link = "https://ceteris.mx/"
      image = "/images/hero-section/ceteris.png"

    [[params.logo_item]]
      name = "SOAINT"
      link = "https://soaint.com/"
      image = "/images/hero-section/soaint.png"

    [[params.logo_item]]
      name = "Accenture"
      link = "https://www.accenture.com/us-en"
      image = "/images/hero-section/accenture.png"

  #-------------------------------
  # Newsletter Settings
  [params.mailchimp]
    enable = false
    mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__input__text = "Your email address..."
    mailchimp__button__text = "Subscribe" # Add your button text


  #-------------------------------
  # Work Settings
  [params.work]
    enable = true
    work__title= "Portafolio"
    work__description= "Explora mis proyectos y descubre cómo puedo ayudar a transformar tus ideas en realidad"


  #-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = false
    testimonial__title = "Clients"
    testimonial__description = ""

  [[params.testimonial_item]]
    name = "Hanna Septimus"
    image = "https://via.placeholder.com/400x400"
    designation = "Product Designer"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Carla Rosser"
    image = "https://via.placeholder.com/400x400"
    designation = "Statistician"
    link = "https://facebook.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Maria Curtis"
    image = "https://via.placeholder.com/400x400"
    designation = "Team Lead"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Carter Bergson"
    image = "https://via.placeholder.com/400x400"
    designation = "CEO, Founder"
    link = "https://facebook.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Jordyn Franci"
    image = "https://via.placeholder.com/400x400"
    designation = "Personal Trainer"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Mira Carder"
    image = "https://via.placeholder.com/400x400"
    designation = "Data Scientist"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Madelyn Herwitz"
    image = "https://via.placeholder.com/400x400"
    designation = "Frontend Engineer"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Anika Schleifer"
    image = "https://via.placeholder.com/400x400"
    designation = "Fitness Director"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  [[params.testimonial_item]]
    name = "Wilson Dorwart"
    image = "https://via.placeholder.com/400x400"
    designation = "Financial Manager"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"


  #-------------------------------
  # Blog Section
  [params.blog]
    enable = true
    blog__title = "Blog"
    blog__description = ""


  #-------------------------------
  # Footer Settings
  [params.footer]
    footer__background__image = "https://via.placeholder.com/1920x1080"


  #-------------------------------
  # Contact Settings
  [params.contact]
    contact__email = "your@email.com" # Add your form_id

    # NOTE
    # Akio theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = true
    disqusShortname = "anvod-studio-test" # Add your shortname for Disqus Comment. For example anvod-studio-test


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false